@host1 = http://localhost:8080

###
GET {{host1}}/

###
POST {{host1}}/echo
Content-Type: application/json

{
    "name": "joe",
    "age": 33
}

###
GET {{host1}}/api/bonus

###
GET {{host1}}/api/bonus/JONES

###
POST {{host1}}/api/bonus
Content-Type: application/json

{
    "ename": "BLAKE",
    "job": "MANAGER",
    "sal": 220,
    "comm": 500
}

###
POST {{host1}}/api/bonus
Content-Type: application/json

{
    "ename": "JONAS",
    "job": "MANAGER",
    "sal": 210,
    "comm": 400
}

###

PUT {{host1}}/api/bonus/ALLEN
Content-Type: application/json

{
    "ename": "ALLEN",
    "job": "SALESMAN",
    "sal": 2000,
    "comm": 320
}
###
DELETE {{host1}}/api/bonus/BLAKE

###
GET {{host1}}/api/dept HTTP/1.1

###
GET {{host1}}/api/dept/20

###
POST  {{host1}}/auth/login
Content-Type: application/json

{
    "uid": "demo",
    "pwd": "123"
}


###
@tok1 = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkZW1vIiwicm9sZSI6InVzZXIiLCJleHAiOjE3MzU5MTkzODR9.6wisJoEygCi76v5NH9ZRoXNEnusDX0Ft8ExcxfMxf80

###
GET  {{host1}}/auth/rnd
Authorization: Bearer {{tok1}}

###




