CREATE TABLE bonus (
    ename TEXT NOT NULL PRIMARY KEY ,
    job TEXT NOT NULL,
    sal INTEGER NOT NULL,
    comm INTEGER NOT NULL
);
CREATE TABLE dept (
    deptno INTEGER NOT NULL PRIMARY KEY,
    dname VARCHAR(14) NOT NULL,
    loc VARCHAR(13) NOT NULL
);

INSERT INTO BONUS VALUES ('ALLEN','SALESMAN',110,300);
INSERT INTO BONUS VALUES ('JONES','MANAGER',2000,500);


INSERT INTO dept VALUES (10, 'ACCOUNTING', 'NEW YORK');
INSERT INTO dept VALUES (20, 'RESEARCH',   'DALLAS');
INSERT INTO dept VALUES (30, 'SALES',      'CHICAGO');
INSERT INTO dept VALUES (40, 'OPERATIONS', 'BOSTON');